// wrapper/svelte/ZikoUI.svelte
<ziko-ui bind:this={containerRef} data-engine="ziko"></ziko-ui>

<script>
  import { onMount } from 'svelte';
  import {ZikoUIElement} from "ziko";
  let containerRef;
  
  onMount(() => {
    if (containerRef && ui instanceof ZikoUIElement) {
      containerRef.innerHTML = "";
      containerRef.appendChild(ui.element);
    }
  });
  export let ui;
</script>

// wrapper/vue/ZikoUI.vue
<template>
  <div ref="containerRef" data-engine="ziko">Test</div>
</template>
<script>
import {ZikoUIElement} from "ziko"
export default {
  props: {
    ui: Object
  },
  mounted() {
    if (this.$refs.containerRef && this.ui instanceof ZikoUIElement) {
      this.$refs.containerRef.innerHTML = "";
      this.$refs.containerRef.appendChild(this.ui.element);
    }
  }
};
</script>
